version: '3.8'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      backend:
        aliases:
          - db
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      backend:
        aliases:
          - app
    env_file:
      - .env
  composer:
    image: composer 
    command: install --ignore-platform-reqs
    volumes: 
      - .:/app 
networks:
  backend:
    name: backend-network
