version: "3"
networks:
  wpsite:
  phpmyadmin:
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: soutenance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - wpsite
      - phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - phpmyadmin
  web:
    image: php:7.2.2-apache
    depends_on:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true