version: '3.8'
services:
  db:
    image: mysql:5.6
    container_name: Database
    environment:
      MYSQL_DATABASE: soutenance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  web:
    image: php:5.6-apache
    container_name: Php