version: '3.8'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: soutenance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php:5.6-apache
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
